"use strict";
//var uss=require("./uss.frame");
//var ussField=require("./uss.field");
var ussfield = require("./field");
var ussframe = require("./frame");
var field=new ussfield.Field();
var frame = new ussframe.Frame();

var schemaJsonRef= [{
    "name" : "employeeLoginDetailsResponse"
    ,"$ref" : "http://localhost:5001/services/schema/loginDetailsResponse#/loginDetailsResponse"
}];

var schemaJson= [
    {
        "group": "USS",
        "name": "loginDetailsResponse",
        "label": "Basic Details",
        "task": "ES",
        "desc": "",
        "htmlType": "PAGE",
        "entitle": "NONREADONLY",
        "enttlname": "255",
        "editorRole": "255",
        "mndf": "Y",
        "dataType": "PAGE",
        "cclass": "ctable",
        "parent": "",
        "parentHtmlType": "",
        "validate": "",
        "dflt": "",
        "min": "0",
        "max": "60",
        "tips": "",
        "onkeyup": "onKeyUp(this);",
        "onchange": "onChange(this);",
        "onkeydown": "onKeyDown(this);",
        "onkeypress": "onKeyPress(this);",
        "onclick": "onClick(this);",
        "onblure": "onBlure(this);",
        "listVal": "0",
        "help": "N",
        "helpLink": "helpload",
        "xml": "Y",
        "xmlname": "",
        "Xpath": "/",
        "maxCol": "1",
        "col": "0",
        "dimensions": "",
        "dimensionMax": "",
        "dimensionMin": "",
        "dataCategory": "PRIMITIVE",
        "iconListVal": "undefined",
        "camelCase": true,
        "childs": [
            {
                "group": "USS",
                "name": "userDetails",
                "label": "",
                "task": "NONE",
                "desc": "",
                "htmlType": "CONTAINER",
                "entitle": "READONLY",
                "enttlname": "255",
                "editorRole": "255",
                "mndf": "Y",
                "dataType": "CONTAINER",
                "cclass": "ctable",
                "parent": "",
                "parentHtmlType": "",
                "validate": "",
                "dflt": "",
                "min": "0",
                "max": "60",
                "tips": "",
                "onkeyup": "onKeyUp(this);",
                "onchange": "onChange(this);",
                "onkeydown": "onKeyDown(this);",
                "onkeypress": "onKeyPress(this);",
                "onclick": "onClick(this);",
                "onblure": "onBlure(this);",
                "listVal": "||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY",
                "help": "N",
                "helpLink": "helpload",
                "xml": "Y",
                "xmlname": "",
                "Xpath": "/",
                "maxCol": "1",
                "col": "0",
                "dimensions": "",
                "dimensionMax": "",
                "dimensionMin": "",
                "dataCategory": "PRIMITIVE",
                "iconListVal": "undefined",
                "camelCase": true,
                "childs": [
                    {
                        "group": "USS",
                        "name": "firstName",
                        "label": "First Name",
                        "task": "NONE",
                        "desc": "",
                        "htmlType": "TEXT",
                        "entitle": "READONLY",
                        "enttlname": "255",
                        "editorRole": "255",
                        "mndf": "Y",
                        "dataType": "VARCHAR",
                        "cclass": "ctable",
                        "parent": "",
                        "parentHtmlType": "",
                        "validate": "",
                        "dflt": "",
                        "min": "0",
                        "max": "60",
                        "tips": "",
                        "onkeyup": "onKeyUp(this);",
                        "onchange": "onChange(this);",
                        "onkeydown": "onKeyDown(this);",
                        "onkeypress": "onKeyPress(this);",
                        "onclick": "onClick(this);",
                        "onblure": "onBlure(this);",
                        "listVal": "||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY",
                        "help": "N",
                        "helpLink": "helpload",
                        "xml": "Y",
                        "xmlname": "",
                        "Xpath": "/",
                        "maxCol": "1",
                        "col": "0",
                        "dimensions": "",
                        "dimensionMax": "",
                        "dimensionMin": "",
                        "dataCategory": "PRIMITIVE",
                        "iconListVal": "undefined",
                        "camelCase": true,
                        "childs": []
                    },
                    {
                        "group": "USS",
                        "name": "lastName",
                        "label": "Last Name",
                        "task": "NONE",
                        "desc": "",
                        "htmlType": "TEXT",
                        "entitle": "READONLY",
                        "enttlname": "255",
                        "editorRole": "255",
                        "mndf": "Y",
                        "dataType": "VARCHAR",
                        "cclass": "ctable",
                        "parent": "",
                        "parentHtmlType": "",
                        "validate": "",
                        "dflt": "",
                        "min": "0",
                        "max": "60",
                        "tips": "",
                        "onkeyup": "onKeyUp(this);",
                        "onchange": "onChange(this);",
                        "onkeydown": "onKeyDown(this);",
                        "onkeypress": "onKeyPress(this);",
                        "onclick": "onClick(this);",
                        "onblure": "onBlure(this);",
                        "listVal": "||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY",
                        "help": "N",
                        "helpLink": "helpload",
                        "xml": "Y",
                        "xmlname": "",
                        "Xpath": "/",
                        "maxCol": "1",
                        "col": "0",
                        "dimensions": "",
                        "dimensionMax": "",
                        "dimensionMin": "",
                        "dataCategory": "PRIMITIVE",
                        "iconListVal": "undefined",
                        "camelCase": true,
                        "childs": []
                    },
                    {
                        "group": "USS",
                        "name": "grpName",
                        "label": "Last Name",
                        "task": "NONE",
                        "desc": "",
                        "htmlType": "TEXT",
                        "entitle": "READONLY",
                        "enttlname": "255",
                        "editorRole": "255",
                        "mndf": "Y",
                        "dataType": "VARCHAR",
                        "cclass": "ctable",
                        "parent": "",
                        "parentHtmlType": "",
                        "validate": "",
                        "dflt": "",
                        "min": "0",
                        "max": "60",
                        "tips": "",
                        "onkeyup": "onKeyUp(this);",
                        "onchange": "onChange(this);",
                        "onkeydown": "onKeyDown(this);",
                        "onkeypress": "onKeyPress(this);",
                        "onclick": "onClick(this);",
                        "onblure": "onBlure(this);",
                        "listVal": "||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY",
                        "help": "N",
                        "helpLink": "helpload",
                        "xml": "Y",
                        "xmlname": "",
                        "Xpath": "/",
                        "maxCol": "1",
                        "col": "0",
                        "dimensions": "",
                        "dimensionMax": "",
                        "dimensionMin": "",
                        "dataCategory": "PRIMITIVE",
                        "iconListVal": "undefined",
                        "camelCase": true,
                        "childs": []
                    },
                    {
                        "group": "USS",
                        "name": "prodVersion",
                        "label": "Product Version",
                        "task": "NONE",
                        "desc": "",
                        "htmlType": "TEXT",
                        "entitle": "READONLY",
                        "enttlname": "255",
                        "editorRole": "255",
                        "mndf": "Y",
                        "dataType": "VARCHAR",
                        "cclass": "ctable",
                        "parent": "",
                        "parentHtmlType": "",
                        "validate": "",
                        "dflt": "",
                        "min": "0",
                        "max": "60",
                        "tips": "",
                        "onkeyup": "onKeyUp(this);",
                        "onchange": "onChange(this);",
                        "onkeydown": "onKeyDown(this);",
                        "onkeypress": "onKeyPress(this);",
                        "onclick": "onClick(this);",
                        "onblure": "onBlure(this);",
                        "listVal": "||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY",
                        "help": "N",
                        "helpLink": "helpload",
                        "xml": "Y",
                        "xmlname": "",
                        "Xpath": "/",
                        "maxCol": "1",
                        "col": "0",
                        "dimensions": "",
                        "dimensionMax": "",
                        "dimensionMin": "",
                        "dataCategory": "PRIMITIVE",
                        "iconListVal": "undefined",
                        "camelCase": true,
                        "childs": []
                    },
                    {
                        "group": "USS",
                        "name": "prtlName",
                        "label": "Portal Name",
                        "task": "NONE",
                        "desc": "",
                        "htmlType": "TEXT",
                        "entitle": "READONLY",
                        "enttlname": "255",
                        "editorRole": "255",
                        "mndf": "Y",
                        "dataType": "VARCHAR",
                        "cclass": "ctable",
                        "parent": "",
                        "parentHtmlType": "",
                        "validate": "",
                        "dflt": "",
                        "min": "0",
                        "max": "60",
                        "tips": "",
                        "onkeyup": "onKeyUp(this);",
                        "onchange": "onChange(this);",
                        "onkeydown": "onKeyDown(this);",
                        "onkeypress": "onKeyPress(this);",
                        "onclick": "onClick(this);",
                        "onblure": "onBlure(this);",
                        "listVal": "||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY",
                        "help": "N",
                        "helpLink": "helpload",
                        "xml": "Y",
                        "xmlname": "",
                        "Xpath": "/",
                        "maxCol": "1",
                        "col": "0",
                        "dimensions": "undefined",
                        "dimensionMax": "",
                        "dimensionMin": "",
                        "dataCategory": "PRIMITIVE",
                        "iconListVal": "undefined",
                        "camelCase": true,
                        "childs": []
                    }
                ]
            },
            {
                "group": "USS",
                "name": "entitlement",
                "label": "Entitlement",
                "task": "NONE",
                "desc": "",
                "htmlType": "CONTAINER",
                "entitle": "READONLY",
                "enttlname": "255",
                "editorRole": "255",
                "mndf": "Y",
                "dataType": "CONTAINER",
                "cclass": "ctable",
                "parent": "",
                "parentHtmlType": "",
                "validate": "",
                "dflt": "",
                "min": "0",
                "max": "60",
                "tips": "",
                "onkeyup": "onKeyUp(this);",
                "onchange": "onChange(this);",
                "onkeydown": "onKeyDown(this);",
                "onkeypress": "onKeyPress(this);",
                "onclick": "onClick(this);",
                "onblure": "onBlure(this);",
                "listVal": "||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY",
                "help": "N",
                "helpLink": "helpload",
                "xml": "Y",
                "xmlname": "",
                "Xpath": "/",
                "maxCol": "1",
                "col": "0",
                "dimensions": "",
                "dimensionMax": "",
                "dimensionMin": "",
                "dataCategory": "PRIMITIVE",
                "iconListVal": "undefined",
                "camelCase": true,
                "childs": [
                    {
                        "group": "USS",
                        "name": "link",
                        "label": "Link",
                        "task": "NONE",
                        "desc": "",
                        "htmlType": "TEXT",
                        "entitle": "READONLY",
                        "enttlname": "255",
                        "editorRole": "255",
                        "mndf": "Y",
                        "dataType": "VARCHAR",
                        "cclass": "ctable",
                        "parent": "",
                        "parentHtmlType": "",
                        "validate": "",
                        "dflt": "",
                        "min": "0",
                        "max": "60",
                        "tips": "",
                        "onkeyup": "onKeyUp(this);",
                        "onchange": "onChange(this);",
                        "onkeydown": "onKeyDown(this);",
                        "onkeypress": "onKeyPress(this);",
                        "onclick": "onClick(this);",
                        "onblure": "onBlure(this);",
                        "listVal": "||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY",
                        "help": "N",
                        "helpLink": "helpload",
                        "xml": "Y",
                        "xmlname": "",
                        "Xpath": "/",
                        "maxCol": "1",
                        "col": "0",
                        "dimensions": "",
                        "dimensionMax": "",
                        "dimensionMin": "",
                        "dataCategory": "PRIMITIVE",
                        "iconListVal": "undefined",
                        "camelCase": true,
                        "childs": []
                    },
                    {
                        "group": "USS",
                        "name": "linkName",
                        "label": "linkName",
                        "task": "NONE",
                        "desc": "",
                        "htmlType": "TEXT",
                        "entitle": "READONLY",
                        "enttlname": "255",
                        "editorRole": "255",
                        "mndf": "Y",
                        "dataType": "VARCHAR",
                        "cclass": "ctable",
                        "parent": "",
                        "parentHtmlType": "",
                        "validate": "",
                        "dflt": "",
                        "min": "0",
                        "max": "60",
                        "tips": "",
                        "onkeyup": "onKeyUp(this);",
                        "onchange": "onChange(this);",
                        "onkeydown": "onKeyDown(this);",
                        "onkeypress": "onKeyPress(this);",
                        "onclick": "onClick(this);",
                        "onblure": "onBlure(this);",
                        "listVal": "||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY",
                        "help": "N",
                        "helpLink": "helpload",
                        "xml": "Y",
                        "xmlname": "",
                        "Xpath": "/",
                        "maxCol": "1",
                        "col": "0",
                        "dimensions": "undefined",
                        "dimensionMax": "",
                        "dimensionMin": "",
                        "dataCategory": "PRIMITIVE",
                        "iconListVal": "undefined",
                        "camelCase": true,
                        "childs": []
                    },
                    {
                        "group": "USS",
                        "name": "uid",
                        "label": "uid",
                        "task": "NONE",
                        "desc": "",
                        "htmlType": "TEXT",
                        "entitle": "READONLY",
                        "enttlname": "255",
                        "editorRole": "255",
                        "mndf": "Y",
                        "dataType": "VARCHAR",
                        "cclass": "ctable",
                        "parent": "",
                        "parentHtmlType": "",
                        "validate": "",
                        "dflt": "",
                        "min": "0",
                        "max": "60",
                        "tips": "",
                        "onkeyup": "onKeyUp(this);",
                        "onchange": "onChange(this);",
                        "onkeydown": "onKeyDown(this);",
                        "onkeypress": "onKeyPress(this);",
                        "onclick": "onClick(this);",
                        "onblure": "onBlure(this);",
                        "listVal": "||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY",
                        "help": "N",
                        "helpLink": "helpload",
                        "xml": "Y",
                        "xmlname": "",
                        "Xpath": "/",
                        "maxCol": "1",
                        "col": "0",
                        "dimensions": "undefined",
                        "dimensionMax": "",
                        "dimensionMin": "",
                        "dataCategory": "PRIMITIVE",
                        "iconListVal": "undefined",
                        "camelCase": true,
                        "childs": []
                    },
                    {
                        "group": "USS",
                        "name": "dataType",
                        "label": "Data type",
                        "task": "NONE",
                        "desc": "",
                        "htmlType": "TEXT",
                        "entitle": "READONLY",
                        "enttlname": "255",
                        "editorRole": "255",
                        "mndf": "Y",
                        "dataType": "LIST",
                        "cclass": "ctable",
                        "parent": "",
                        "parentHtmlType": "",
                        "validate": "",
                        "dflt": "",
                        "min": "0",
                        "max": "60",
                        "tips": "",
                        "onkeyup": "onKeyUp(this);",
                        "onchange": "onChange(this);",
                        "onkeydown": "onKeyDown(this);",
                        "onkeypress": "onKeyPress(this);",
                        "onclick": "onClick(this);",
                        "onblure": "onBlure(this);",
                        "listVal": "CONTAINER|CONTAINER|NODE|NODE",
                        "help": "N",
                        "helpLink": "helpload",
                        "xml": "Y",
                        "xmlname": "",
                        "Xpath": "/",
                        "maxCol": "1",
                        "col": "0",
                        "dimensions": "",
                        "dimensionMax": "",
                        "dimensionMin": "",
                        "dataCategory": "PRIMITIVE",
                        "iconListVal": "undefined",
                        "camelCase": true,
                        "childs": []
                    },
                    {
                        "group": "USS",
                        "name": "childs",
                        "label": "Childs",
                        "task": "NONE",
                        "desc": "",
                        "htmlType": "TEXT",
                        "entitle": "READONLY",
                        "enttlname": "255",
                        "editorRole": "255",
                        "mndf": "Y",
                        "dataType": "CONTAINER",
                        "cclass": "ctable",
                        "parent": "",
                        "parentHtmlType": "",
                        "validate": "",
                        "dflt": "",
                        "min": "0",
                        "max": "60",
                        "tips": "",
                        "onkeyup": "onKeyUp(this);",
                        "onchange": "onChange(this);",
                        "onkeydown": "onKeyDown(this);",
                        "onkeypress": "onKeyPress(this);",
                        "onclick": "onClick(this);",
                        "onblure": "onBlure(this);",
                        "listVal": "||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY",
                        "help": "N",
                        "helpLink": "helpload",
                        "xml": "Y",
                        "xmlname": "",
                        "Xpath": "/",
                        "maxCol": "1",
                        "col": "0",
                        "dimensions": "",
                        "dimensionMax": "",
                        "dimensionMin": "",
                        "dataCategory": "PRIMITIVE",
                        "iconListVal": "undefined",
                        "camelCase": true,
                        "childs": [
{
                        "group": "USS",
                        "name": "link",
                        "label": "Link",
                        "task": "NONE",
                        "desc": "",
                        "htmlType": "TEXT",
                        "entitle": "READONLY",
                        "enttlname": "255",
                        "editorRole": "255",
                        "mndf": "Y",
                        "dataType": "VARCHAR",
                        "cclass": "ctable",
                        "parent": "",
                        "parentHtmlType": "",
                        "validate": "",
                        "dflt": "",
                        "min": "0",
                        "max": "60",
                        "tips": "",
                        "onkeyup": "onKeyUp(this);",
                        "onchange": "onChange(this);",
                        "onkeydown": "onKeyDown(this);",
                        "onkeypress": "onKeyPress(this);",
                        "onclick": "onClick(this);",
                        "onblure": "onBlure(this);",
                        "listVal": "||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY",
                        "help": "N",
                        "helpLink": "helpload",
                        "xml": "Y",
                        "xmlname": "",
                        "Xpath": "/",
                        "maxCol": "1",
                        "col": "0",
                        "dimensions": "",
                        "dimensionMax": "",
                        "dimensionMin": "",
                        "dataCategory": "PRIMITIVE",
                        "iconListVal": "undefined",
                        "camelCase": true,
                        "childs": []
                    },
                    {
                        "group": "USS",
                        "name": "linkName",
                        "label": "linkName",
                        "task": "NONE",
                        "desc": "",
                        "htmlType": "TEXT",
                        "entitle": "READONLY",
                        "enttlname": "255",
                        "editorRole": "255",
                        "mndf": "Y",
                        "dataType": "VARCHAR",
                        "cclass": "ctable",
                        "parent": "",
                        "parentHtmlType": "",
                        "validate": "",
                        "dflt": "",
                        "min": "0",
                        "max": "60",
                        "tips": "",
                        "onkeyup": "onKeyUp(this);",
                        "onchange": "onChange(this);",
                        "onkeydown": "onKeyDown(this);",
                        "onkeypress": "onKeyPress(this);",
                        "onclick": "onClick(this);",
                        "onblure": "onBlure(this);",
                        "listVal": "||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY",
                        "help": "N",
                        "helpLink": "helpload",
                        "xml": "Y",
                        "xmlname": "",
                        "Xpath": "/",
                        "maxCol": "1",
                        "col": "0",
                        "dimensions": "undefined",
                        "dimensionMax": "",
                        "dimensionMin": "",
                        "dataCategory": "PRIMITIVE",
                        "iconListVal": "undefined",
                        "camelCase": true,
                        "childs": []
                    },
                    {
                        "group": "USS",
                        "name": "uid",
                        "label": "uid",
                        "task": "NONE",
                        "desc": "",
                        "htmlType": "TEXT",
                        "entitle": "READONLY",
                        "enttlname": "255",
                        "editorRole": "255",
                        "mndf": "Y",
                        "dataType": "VARCHAR",
                        "cclass": "ctable",
                        "parent": "",
                        "parentHtmlType": "",
                        "validate": "",
                        "dflt": "",
                        "min": "0",
                        "max": "60",
                        "tips": "",
                        "onkeyup": "onKeyUp(this);",
                        "onchange": "onChange(this);",
                        "onkeydown": "onKeyDown(this);",
                        "onkeypress": "onKeyPress(this);",
                        "onclick": "onClick(this);",
                        "onblure": "onBlure(this);",
                        "listVal": "||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY",
                        "help": "N",
                        "helpLink": "helpload",
                        "xml": "Y",
                        "xmlname": "",
                        "Xpath": "/",
                        "maxCol": "1",
                        "col": "0",
                        "dimensions": "undefined",
                        "dimensionMax": "",
                        "dimensionMin": "",
                        "dataCategory": "PRIMITIVE",
                        "iconListVal": "undefined",
                        "camelCase": true,
                        "childs": []
                    },
                    {
                        "group": "USS",
                        "name": "dataType",
                        "label": "Data type",
                        "task": "NONE",
                        "desc": "",
                        "htmlType": "TEXT",
                        "entitle": "READONLY",
                        "enttlname": "255",
                        "editorRole": "255",
                        "mndf": "Y",
                        "dataType": "LIST",
                        "cclass": "ctable",
                        "parent": "",
                        "parentHtmlType": "",
                        "validate": "",
                        "dflt": "",
                        "min": "0",
                        "max": "60",
                        "tips": "",
                        "onkeyup": "onKeyUp(this);",
                        "onchange": "onChange(this);",
                        "onkeydown": "onKeyDown(this);",
                        "onkeypress": "onKeyPress(this);",
                        "onclick": "onClick(this);",
                        "onblure": "onBlure(this);",
                        "listVal": "CONTAINER|CONTAINER|NODE|NODE",
                        "help": "N",
                        "helpLink": "helpload",
                        "xml": "Y",
                        "xmlname": "",
                        "Xpath": "/",
                        "maxCol": "1",
                        "col": "0",
                        "dimensions": "",
                        "dimensionMax": "",
                        "dimensionMin": "",
                        "dataCategory": "PRIMITIVE",
                        "iconListVal": "undefined",
                        "camelCase": true,
                        "childs": []
                    },
                    {
                        "group": "USS",
                        "name": "childs",
                        "label": "Childs",
                        "task": "NONE",
                        "desc": "",
                        "htmlType": "TEXT",
                        "entitle": "READONLY",
                        "enttlname": "255",
                        "editorRole": "255",
                        "mndf": "Y",
                        "dataType": "CONTAINER",
                        "cclass": "ctable",
                        "parent": "",
                        "parentHtmlType": "",
                        "validate": "",
                        "dflt": "",
                        "min": "0",
                        "max": "60",
                        "tips": "",
                        "onkeyup": "onKeyUp(this);",
                        "onchange": "onChange(this);",
                        "onkeydown": "onKeyDown(this);",
                        "onkeypress": "onKeyPress(this);",
                        "onclick": "onClick(this);",
                        "onblure": "onBlure(this);",
                        "listVal": "||A|A-ADD|M|M-MODIFY|I|I-INQURY|C|C-CANCEL|V|V-VERIFY",
                        "help": "N",
                        "helpLink": "helpload",
                        "xml": "Y",
                        "xmlname": "",
                        "Xpath": "/",
                        "maxCol": "1",
                        "col": "0",
                        "dimensions": "",
                        "dimensionMax": "",
                        "dimensionMin": "",
                        "dataCategory": "PRIMITIVE",
                        "iconListVal": "undefined",
                        "camelCase": true,
                        "childs": []
                    }
                        ]
                    }
                ]
            }
        ]
    }
];

var generateSchemaContext = function (schemaJson, uri) {
    var context = [];
    var contextObj={};
    if (!uri) {
        uri = "http://localhost:5001/services/schema/" + schemaJson[0].name + "#";
    }
    schemaJson.forEach(function(schemaJsonObj) {
        var key =uri + "/" + schemaJsonObj.name;
        contextObj[key] = schemaJsonObj;
        if (hasChild(schemaJsonObj)) {
            generateSchemaContext(schemaJsonObj.childs, key).forEach(function(childObj) {
                for (var key in childObj) {
                    contextObj[key]=childObj[key];
                }
            });
        }
        context.push(contextObj);
        console.log(JSON.stringify(contextObj, null, 4));
    }); 
    return  context;
}
var hasChild=function(schemaJsonObj) {
    if (schemaJsonObj.childs || Array.isArray(schemaJsonObj.childs) || schemaJsonObj.childs.length !=0) {
        return true
    }
    return false;
}
var context=generateSchemaContext(schemaJson);

console.log(context[0]["http://localhost:5001/services/schema/loginDetailsResponse#/loginDetailsResponse/userDetails/prtlName"]);

var generateSchemaJson = function(schemaJsonRef, context) {
    var schemaJson=[];
    schemaJsonRef.forEach(function(schemaJsonRefObj) {
        if (schemaJsonRefObj.$ref) {
           var contextObj=context[0][schemaJsonRefObj.$ref];
            for (var key in schemaJsonRefObj)  {
                if (key != "$ref") {
                    contextObj[key]=schemaJsonRefObj[key];
                }
            }
            schemaJson.push(contextObj);
        } else {
            schemaJson.push(schemaJsonRefObj);
        }
    });
    return schemaJson;
}

var employeeSchema=generateSchemaJson(schemaJsonRef, context);
console.log(employeeSchema);
console.log(JSON.stringify(employeeSchema, null, 4));

/*
var ussSchemaJsonDraft07=require("./ussSchemaJson");
console.log(ussSchemaJsonDraft07);
console.log(ussSchemaJsonDraft07.$id);
console.log(ussSchemaJsonDraft07.$schema);
console.log(ussSchemaJsonDraft07.default);
console.log(ussSchemaJsonDraft07.definitions);
console.log(ussSchemaJsonDraft07.properties);
console.log(ussSchemaJsonDraft07.title);
console.log(ussSchemaJsonDraft07.type);
console.log(ussSchemaJsonDraft07.required);
*/

/*

$id:"http://json-schema.org/draft-07/schema#"
$schema:"http://json-schema.org/draft-07/schema#"
default:true
definitions:Object {schemaArray: Object, nonNegativeInteger: Object, nonNegativeIntegerDefault0: Object, …}
properties:Object {$id: Object, $schema: Object, $ref: Object, …}
title:"Core schema meta-schema"
type:Array(2) ["object", "boolean"]


generateGenerateNameSpace = function (schemaJson) {
    if (Array.isArray(schemaJson)) {
        schemaJson.forEach(function (schemaJsonObj) {
            if (Array.isArray(schemaJsonObj.childs)) {
                
            }
        });
    }
}

schemaJson

frame.isValidate();
*/

//uss.print(frame);